### ISSUE TITLE
Question: How much ignored messages should be within a regular expression until the performance gets down?

### ISSUE THREAD

**Issue by josefglatz** [networkteam/sentry_client#108]
Hi,

due to the fact that many exceptions are coming from 3rd party extension it's not that easy to fix all of them.

Is there a max  number of messages which you put in the regular expression as a maximum value?

**Comment by christophlehmann** [comment]
I bet `preg_match()` has a limit, never checked. 

It could be cleaner to have a list of regular expressions (that needs to go to EXTCONF)

```yaml
EXTCONF:
  sentry_client:
    ignoreMessageRegexp:
      # Bots on Powermail forms
      - 'Required argument.*mail.*Powermail.*FormController.*create'
      # Forbidden backend access (https://review.typo3.org/c/Packages/TYPO3.CMS/+/84726)
      - 'The IP address of your client does not match the list of allowed IP addresses'
```

What do you think?
